parameters:
- name: tasks
  displayName: Tasks to process (separate by colons, no whitespaces)
  type: string
  default: DownloadPackageV1
- name: BuildSourceVersion
  displayName: The latest version control change of the triggering repo that is included in this build.
  type: string

trigger: none
pr: none

stages:
- stage: Test
  jobs:
    - ${{ each task in split(parameters.tasks, ',') }}:
      - job: ${{ task }}_test_task
        displayName: Test (${{ task }})
        pool:
          vmImage: windows-2022
        steps:
        - template: ./test-task.yml
          parameters:
            task: ${{ task }}
            BuildSourceVersion: ${{ parameters.BuildSourceVersion }}

